sudo: required # needed for trusty beta
dist: trusty   # needed for HarfBuzz

os:
  - linux
  - osx

language: c

compiler:
  - gcc
  - clang

env:
  global:
    - CFLAGS=-Werror

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libharfbuzz-dev libfribidi-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install harfbuzz fribidi; fi;

script:
  - make
  - make check

notifications:
  email:
    recipients:
      - host-oman@googlegroups.com
